### ISSUE TITLE
UX: Windows Download Is Not Intuitive

### ISSUE THREAD

**Issue by ChandlerFerry** [VolkshashDEV/volkshashcore#2]
## Problem:
0. Install 7zip
1. Extract the `Volkshash.Windows.x86.0.13.2.1.tar.bz2`
2. Extract the `Volkshash.Windows.x86.0.13.2.1.tar`
3. Rename `.exe__` to `.exe`

## Solution:
1. Zip it as a `.zip` file rather than a tar.bz2
2. Rename `.exe__` to `.exe` during the build process

**Comment by VolkshashDEV** [comment]
All files have been moved to .zip and should be fine now
